# Generated by Django 4.2.16 on 2024-11-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=300)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("1", "Family"),
                            ("2", "Presidential"),
                            ("3", "Executive"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
