# Generated by Django 4.2.16 on 2024-11-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Rooms", new_name="Room",),
    ]
