# Generated by Django 4.2.16 on 2024-11-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_rename_rooms_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[("1", "Family"), ("2", "Presidential"), ("3", "Single")],
                default="1",
                max_length=20,
            ),
        ),
    ]
