# Generated by Django 4.2.16 on 2024-11-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0003_alter_room_room_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarouselImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Carousel-image", max_length=150)),
                ("image", models.ImageField(upload_to="carousel/")),
            ],
        ),
    ]
