# Generated by Django 4.2.16 on 2024-11-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0004_carouselimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("Family", "Family"),
                    ("Presidential", "Presidential"),
                    ("Single", "Single"),
                ],
                default="1",
                max_length=20,
            ),
        ),
    ]
