# Generated by Django 4.2.16 on 2024-11-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0006_room_slug_alter_room_room_type_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
