# Generated by Django 4.2.16 on 2024-11-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0007_alter_room_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="room", name="slug",),
    ]
